/**
 * Generates `src/styles/tokens.css` from the single source of truth,
 * `@acplatform/design-tokens`. This keeps CSS custom properties in sync
 * with the shared token package instead of hand-duplicating values —
 * run automatically before `dev`/`build` (see package.json `predev`/
 * `prebuild`) and can be re-run manually via `npm run tokens:generate`.
 *
 * Do not hand-edit the generated `tokens.css` file; change the token
 * values in `packages/design-tokens` instead (that package is shared
 * with mobile and is not owned by the frontend app).
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { color, minTouchTargetPx, radius, spacing, typography } from "@acplatform/design-tokens";

const outPath = resolve(dirname(fileURLToPath(import.meta.url)), "../src/styles/tokens.css");

function toKebabCase(input: string): string {
  return input.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function flatten(prefix: string, source: Record<string, unknown>, lines: string[]): void {
  for (const [key, value] of Object.entries(source)) {
    const varName = `${prefix}-${toKebabCase(key)}`;
    if (isPlainObject(value)) {
      flatten(varName, value, lines);
    } else {
      const cssValue = typeof value === "number" ? `${value}px` : String(value);
      lines.push(`  --${varName}: ${cssValue};`);
    }
  }
}

const lines: string[] = [];
flatten("color", color, lines);
flatten("spacing", spacing, lines);
flatten("radius", radius, lines);
flatten("typography", typography, lines);
lines.push(`  --min-touch-target-px: ${minTouchTargetPx}px;`);

const banner = `/**
 * GENERATED FILE — do not hand-edit.
 * Generated by scripts/generate-design-tokens.ts from
 * @acplatform/design-tokens. Re-run \`npm run tokens:generate\` after that
 * package's token values change (also runs automatically before
 * \`npm run dev\` / \`npm run build\`).
 */
:root {
${lines.join("\n")}
}
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, banner, "utf8");
console.log(`[tokens] wrote ${lines.length} custom properties to ${outPath}`);
